name: Development Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-dev:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
            os: 'windows'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            os: 'macos'
          - platform: 'ubuntu-latest'
            args: '--target x86_64-unknown-linux-gnu'
            os: 'linux'

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.args == '--target x86_64-pc-windows-msvc' && 'x86_64-pc-windows-msvc' || matrix.args == '--target x86_64-apple-darwin' && 'x86_64-apple-darwin' || 'x86_64-unknown-linux-gnu' }}

    - name: Install dependencies (Ubuntu only)
      if: matrix.os == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install frontend dependencies
      run: npm ci

    - name: Build the app
      run: npm run build ${{ matrix.args }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: calculator-dev-${{ matrix.os }}
        path: |
          src-tauri/target/release/bundle/
        retention-days: 7
